### ISSUE TITLE
TypeError: __init__() missing 2 required positional arguments: 'inputs' and 'outputs'

### ISSUE THREAD

**Issue by mrgloom** [avivga/style-image-prior#1]
```
python -c "import keras; print(keras.__version__)"
Using TensorFlow backend.
2.1.6
```

```
Traceback (most recent call last):
  File "inversion.py", line 109, in <module>
    optimize_latent_codes(args)
  File "inversion.py", line 44, in optimize_latent_codes
    perceptual_model = PerceptualModel(img_size=args.perceptual_img_size)
  File "/data/style-image-prior/perceptual_model.py", line 9, in __init__
    super().__init__()
  File "/usr/local/lib/python3.6/dist-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
TypeError: __init__() missing 2 required positional arguments: 'inputs' and 'outputs'
```

What version of keras did you use?

**Comment by mrgloom** [comment]
After installed newer keras:
```
python -c "import keras; print(keras.__version__)"
Using TensorFlow backend.
2.2.5
```

```
python -c "import tensorflow; print(tensorflow.__version__)"
1.14.0
```

Get another error:
```
tensorflow.python.framework.errors_impl.InvalidArgumentError: Conv2DCustomBackpropInputOp only supports NHWC.
	 [[{{node G_synthesis_2/cond/cond/cond/cond/128x128/Conv0_up/conv2d_transpose}}]]
```

**Comment by mrgloom** [comment]
Looks like the problem stylegan can't be runned on CPU

this not helped me:
https://github.com/igul222/improved_wgan_training/issues/11#issuecomment-294666137

**Comment by avivga** [comment]
Thanks for your interest.

As you have already noticed, stylegan is built to be executed on a GPU and will not run on a CPU out of the box. You might need to alter all the GPU-specific code.
